import NavbarV2 from "@/components/module/Navbar/V2";

export default function page() {
  return (
    <main className="min-h-full bg-neutral-100">
      <NavbarV2>
        <div className="p-12">
          <h1>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Assumenda quod ipsa laborum sequi. Ad quidem ab quae delectus illum aut maxime nihil. Vitae minus blanditiis sequi obcaecati consequuntur mollitia voluptate labore culpa, ad molestias rerum repellat maiores, temporibus nihil provident non dolores omnis, nam asperiores. Odio ipsum aut excepturi nobis autem consectetur voluptates sunt facilis quae explicabo architecto, ullam a in necessitatibus, ratione vitae sint nulla, harum commodi labore temporibus pariatur. Distinctio asperiores inventore consectetur est quod libero architecto delectus maiores accusamus cum dolore officia quidem repudiandae, modi beatae corrupti nihil expedita nam placeat. Ipsum recusandae minus numquam veniam fugiat consequuntur beatae labore repellat enim aliquid alias aperiam provident laboriosam minima, assumenda animi optio exercitationem sequi maxime! Facilis saepe quam illum minima, labore dolorem autem iusto cum illo corporis beatae porro magni eius error ipsam perspiciatis fuga accusamus quia. Voluptatibus hic, pariatur ullam nisi sit rerum explicabo id maxime voluptates nobis reiciendis at maiores dolorem quisquam aut incidunt ducimus, adipisci debitis deserunt distinctio. Architecto amet quis mollitia culpa unde. Asperiores autem nostrum qui ut numquam sapiente debitis. Et obcaecati quos possimus itaque est corporis facere recusandae sed earum ducimus culpa enim dolores assumenda animi sapiente, nemo numquam ipsam. Quas neque soluta, ex eius fugiat accusantium voluptate laudantium ut? Officiis, neque facere! Aspernatur quisquam laborum earum ad sequi impedit atque fugiat voluptatibus laudantium quas ipsam expedita unde dolores reiciendis, optio rerum quos eius consequuntur saepe adipisci nostrum eligendi ipsa nisi distinctio! Minima adipisci nostrum dolorem illum vitae repudiandae eos aliquid voluptates accusantium commodi maiores dolorum suscipit perferendis totam eius porro, laboriosam pariatur autem explicabo
            ullam nobis sint dicta earum. Quae modi impedit distinctio officiis, eaque cum rem amet totam enim facere! Tempora neque asperiores nesciunt sequi iure error beatae itaque doloribus deleniti deserunt illo soluta reiciendis ipsa fugiat voluptatum laudantium saepe debitis, explicabo earum architecto aspernatur repellat magni ducimus nisi! Earum, id rerum atque minus officia inventore eligendi ipsum. Minima quos dolorum accusamus totam cumque officiis sed, dicta temporibus magni consequuntur laborum odit tempore quibusdam culpa similique animi earum ipsum veritatis reprehenderit! Neque, at eius enim omnis culpa dolor reprehenderit aliquid eos qui exercitationem eveniet optio eum aliquam error. Nobis dolor, fugit veritatis, voluptate adipisci placeat itaque modi iusto quibusdam temporibus aspernatur error repellendus ut quidem sed nemo autem minima labore obcaecati, accusamus magni magnam. Assumenda voluptatum nesciunt vel aut in, explicabo ea quidem nihil voluptatem animi odit voluptates, esse mollitia quia libero quibusdam et impedit optio ex labore? Minima doloribus reprehenderit mollitia repudiandae ipsum ut eligendi maiores illum eaque repellat amet, rerum fuga ex ab. Explicabo, illum eaque! Minus ullam libero eum? Cum quae possimus nesciunt illo minus expedita neque temporibus tempore reprehenderit? Reprehenderit dolorum voluptatibus recusandae, enim eos illum praesentium facere cum itaque sit deleniti? Officia enim magnam quibusdam illo est facilis, quam numquam eos dignissimos quae excepturi deleniti. Voluptate cumque quidem quibusdam voluptatem quaerat error eaque labore veniam qui eius ullam, esse in sint ut, blanditiis, velit fuga deleniti dicta autem architecto officia temporibus modi eum non? Mollitia voluptatibus delectus obcaecati culpa saepe ex, aspernatur repellat architecto alias consectetur deserunt cum? Modi architecto, minus voluptatem rem aliquam debitis voluptas mollitia deserunt ipsum consequatur nostrum, cumque esse tempore! Dolor,
            qui minima voluptatem deserunt perferendis, quibusdam beatae voluptatibus exercitationem voluptas iusto itaque facere dolore odio omnis veritatis, quas magnam consequatur quia? Facere unde fugiat aperiam nesciunt sequi! Beatae, fuga magnam eaque accusamus obcaecati tempora voluptas rem doloremque officia, odio ipsum, natus aliquam vel quaerat perferendis suscipit nihil! Quam ducimus vitae obcaecati, repellat aperiam aliquid repudiandae provident. Dicta commodi molestiae aut accusantium voluptate. Esse cumque magni iure laboriosam ducimus possimus, aut dignissimos, dolor impedit unde quam rerum enim sint porro facilis numquam. Consequuntur aut blanditiis praesentium enim saepe nulla ex, vero voluptatum doloribus incidunt pariatur accusamus quam! Sunt dolorem dolore ad iusto molestiae similique impedit temporibus accusamus tenetur nostrum id animi illo, esse aspernatur maxime aliquam? Rem quam distinctio voluptatem eaque deleniti molestiae aspernatur, soluta unde praesentium culpa corrupti? Aspernatur, nesciunt fugit sint iure delectus, soluta harum deleniti perferendis non sequi placeat molestiae impedit fugiat pariatur obcaecati consequuntur iusto aut asperiores culpa eaque omnis voluptate. Aspernatur autem laudantium saepe aut blanditiis ad quaerat architecto facilis ex? Molestiae non veniam molestias, sunt vitae rem odio suscipit quisquam dolor mollitia facere minus quas nulla reiciendis eligendi fugit! Impedit odit nostrum cumque, quam sit harum voluptate nesciunt facilis numquam minima necessitatibus officiis eligendi libero voluptatum. Ad, maxime. Repellat quisquam, vel ipsa quibusdam quis repellendus. Suscipit pariatur accusantium aliquam modi non quaerat ipsum rem voluptatem eius. Dicta eum quasi dignissimos quaerat eaque blanditiis ea ut mollitia delectus laudantium rem, vel tenetur sit iste? Atque est quo adipisci necessitatibus assumenda neque deserunt at distinctio dolor nemo, quasi quae ab officia blanditiis vitae, alias nam eaque excepturi
            commodi. Assumenda deserunt eos distinctio earum quisquam quasi, nesciunt nulla rem, ea ipsum sunt eius delectus sint accusantium cum repudiandae amet officiis nemo, odio repellat officia exercitationem. Aliquid beatae esse, ut minima dignissimos voluptatum nesciunt, distinctio quibusdam illum nobis delectus consequatur cumque facilis impedit? Dignissimos repellendus, fuga voluptatum magni doloribus aperiam, explicabo dolor esse sit laudantium qui delectus eum perferendis harum necessitatibus impedit, odit asperiores. Cupiditate quisquam ratione ut necessitatibus fuga, repudiandae itaque consectetur quos magni explicabo nemo quis ipsa sapiente nisi, consequatur laudantium nobis vero aliquid vitae officia amet nostrum aut voluptate corporis. Enim veritatis blanditiis magni praesentium? Quaerat itaque explicabo, odio ipsa fugit sunt optio beatae perspiciatis atque amet debitis deserunt modi placeat, quia accusantium et numquam illum nihil corporis libero ullam? Saepe ipsum ex corporis dicta neque reiciendis fuga repellat odit porro eos, quas qui id ullam asperiores eum sequi amet animi quod pariatur nulla eius vero atque nemo dolor. Dolorum doloribus maiores expedita officiis blanditiis, culpa nesciunt est. Corrupti eius voluptate corporis perspiciatis nemo fugit. Dignissimos enim tenetur officiis numquam impedit nesciunt animi quaerat doloremque temporibus quod ipsum doloribus modi, deleniti consequuntur adipisci expedita ipsam corporis vitae delectus nemo velit tempora sequi? Facere delectus amet optio tenetur quia sint architecto, vero maiores ipsam, dolorem laboriosam quod!
          </h1>
        </div>
      </NavbarV2>
    </main>
  );
}
